/**
 * Signal Delivery Service
 * Handles delivery of trading signals to Discord, IB Gateway, and other channels
 */

import { discordAPI } from './discord';
import { createClient } from '@supabase/supabase-js';
import { realIBGatewayClient as ibGatewayClient, executeTradeSignal } from './real-ib-gateway-client';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export interface TradingSignal {
  id?: string;
  symbol: string;
  direction: 'LONG' | 'SHORT';
  entry_price: number;
  stop_loss: number;
  target_price_1?: number;
  target_price_2?: number;
  target_price_3?: number;
  confidence_level: number;
  strategy: string;
  timeframe: string;
  notes?: string;
  created_at?: string;
}

export interface SignalDeliveryResult {
  success: boolean;
  signalId?: string;
  discord?: {
    sent: boolean;
    messageId?: string;
    error?: string;
  };
  database?: {
    saved: boolean;
    error?: string;
  };
  ibGateway?: {
    executed: boolean;
    orderId?: number;
    error?: string;
  };
  email?: {
    sent: boolean;
    error?: string;
  };
}

/**
 * Deliver a trading signal to Discord with rich formatting
 */
export async function deliverSignalToDiscord(signal: TradingSignal): Promise<{
  success: boolean;
  messageId?: string;
  error?: string;
}> {
  try {
    console.log(`📤 Delivering signal to Discord: ${signal.symbol} ${signal.direction}`);

    // Calculate risk/reward metrics
    const risk = Math.abs(signal.entry_price - signal.stop_loss);
    const reward = signal.target_price_1 
      ? Math.abs(signal.target_price_1 - signal.entry_price) 
      : 0;
    const riskRewardRatio = risk > 0 ? (reward / risk).toFixed(2) : '0';

    // Determine color based on direction
    const color = signal.direction === 'LONG' ? 0x10b981 : 0xef4444; // Green for LONG, Red for SHORT

    // Determine confidence color
    let confidenceColor = '🟢';
    if (signal.confidence_level < 75) confidenceColor = '🔴';
    else if (signal.confidence_level < 85) confidenceColor = '🟡';

    // Build targets string
    const targets = [];
    if (signal.target_price_1) targets.push(`T1: $${signal.target_price_1.toFixed(2)}`);
    if (signal.target_price_2) targets.push(`T2: $${signal.target_price_2.toFixed(2)}`);
    if (signal.target_price_3) targets.push(`T3: $${signal.target_price_3.toFixed(2)}`);
    const targetsString = targets.length > 0 ? targets.join(' | ') : 'No targets set';

    // Create rich embed
    const embed = {
      embeds: [{
        title: `🚨 NEW TRADING SIGNAL: ${signal.symbol}`,
        description: signal.notes || 'Professional trading signal generated by Nexural Trading AI',
        color: color,
        fields: [
          {
            name: '📊 Symbol',
            value: `**${signal.symbol}**`,
            inline: true
          },
          {
            name: '📈 Direction',
            value: `**${signal.direction === 'LONG' ? '🟢 LONG' : '🔴 SHORT'}**`,
            inline: true
          },
          {
            name: '🎯 Confidence',
            value: `${confidenceColor} **${signal.confidence_level}%**`,
            inline: true
          },
          {
            name: '💰 Entry Price',
            value: `$${signal.entry_price.toFixed(2)}`,
            inline: true
          },
          {
            name: '🛑 Stop Loss',
            value: `$${signal.stop_loss.toFixed(2)}`,
            inline: true
          },
          {
            name: '⚖️ Risk/Reward',
            value: `1:${riskRewardRatio}`,
            inline: true
          },
          {
            name: '🎯 Targets',
            value: targetsString,
            inline: false
          },
          {
            name: '⏰ Timeframe',
            value: signal.timeframe,
            inline: true
          },
          {
            name: '🧠 Strategy',
            value: signal.strategy,
            inline: true
          },
          {
            name: '📉 Risk Amount',
            value: `$${risk.toFixed(2)}`,
            inline: true
          }
        ],
        timestamp: new Date().toISOString(),
        footer: {
          text: 'Nexural Trading • Professional Signals • Trade at your own risk'
        }
      }]
    };

    // Get signals channel ID (fallback to general if not set)
    const signalsChannelId = process.env.DISCORD_SIGNALS_CHANNEL_ID || 
                             process.env.DISCORD_GENERAL_CHANNEL_ID!;

    // Send to Discord
    const sent = await discordAPI.sendRichEmbed(signalsChannelId, embed);

    if (sent) {
      console.log(`✅ Signal delivered to Discord: ${signal.symbol}`);
      
      // Log delivery to database
      if (signal.id) {
        await logSignalDelivery(signal.id, 'discord', 'delivered');
      }

      return {
        success: true,
        messageId: 'sent' // Discord API doesn't return message ID in our current implementation
      };
    } else {
      throw new Error('Discord API returned false');
    }

  } catch (error) {
    console.error('❌ Signal delivery to Discord failed:', error);
    
    // Log failure to database
    if (signal.id) {
      await logSignalDelivery(
        signal.id, 
        'discord', 
        'failed', 
        error instanceof Error ? error.message : 'Unknown error'
      );
    }

    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Save signal to database
 */
export async function saveSignalToDatabase(signal: TradingSignal): Promise<{
  success: boolean;
  signalId?: string;
  error?: string;
}> {
  try {
    console.log(`💾 Saving signal to database: ${signal.symbol} ${signal.direction}`);

    const { data, error } = await supabase
      .from('trading_signals')
      .insert({
        symbol: signal.symbol,
        direction: signal.direction,
        entry_price: signal.entry_price,
        stop_loss: signal.stop_loss,
        target_price_1: signal.target_price_1,
        target_price_2: signal.target_price_2,
        target_price_3: signal.target_price_3,
        confidence_level: signal.confidence_level,
        strategy: signal.strategy,
        timeframe: signal.timeframe,
        notes: signal.notes,
        status: 'ACTIVE',
        created_at: new Date().toISOString()
      })
      .select()
      .single();

    if (error) {
      console.error('❌ Database save failed:', error);
      return {
        success: false,
        error: error.message
      };
    }

    console.log(`✅ Signal saved to database with ID: ${data.id}`);
    return {
      success: true,
      signalId: data.id
    };

  } catch (error) {
    console.error('❌ Database save error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Execute signal on IB Gateway (Paper Trading)
 */
export async function executeSignalOnIBGateway(signal: TradingSignal, positionSize: number = 1): Promise<{
  success: boolean;
  orderId?: number;
  error?: string;
}> {
  try {
    console.log(`🤖 Executing signal on IB Gateway: ${signal.symbol} ${signal.direction}`);

    // Check if IB Gateway is connected
    if (!ibGatewayClient.isConnectionHealthy()) {
      console.log('📡 IB Gateway not connected, attempting to connect...');
      const connected = await ibGatewayClient.connect();
      
      if (!connected) {
        throw new Error('Failed to connect to IB Gateway');
      }
    }

    // Execute the signal as a market order
    const orderId = await executeTradeSignal({
      symbol: signal.symbol,
      direction: signal.direction,
      quantity: positionSize,
      orderType: 'MKT', // Market order for immediate execution
      limitPrice: signal.entry_price,
    });

    console.log(`✅ Signal executed on IB Gateway - Order ID: ${orderId}`);

    // Log execution to database
    if (signal.id) {
      await logSignalDelivery(signal.id, 'ibgateway' as any, 'delivered');
    }

    return {
      success: true,
      orderId
    };

  } catch (error) {
    console.error('❌ IB Gateway execution failed:', error);

    // Log failure to database
    if (signal.id) {
      await logSignalDelivery(
        signal.id,
        'ibgateway' as any,
        'failed',
        error instanceof Error ? error.message : 'Unknown error'
      );
    }

    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Complete signal delivery pipeline
 */
export async function deliverSignal(
  signal: TradingSignal,
  options: {
    sendToDiscord?: boolean;
    saveToDatabase?: boolean;
    executeOnIBGateway?: boolean;
    positionSize?: number;
    sendEmail?: boolean;
  } = {}
): Promise<SignalDeliveryResult> {
  const {
    sendToDiscord = true,
    saveToDatabase = true,
    executeOnIBGateway = false,
    positionSize = 1,
    sendEmail = false
  } = options;

  const result: SignalDeliveryResult = {
    success: true
  };

  try {
    // 1. Save to database first
    if (saveToDatabase) {
      const dbResult = await saveSignalToDatabase(signal);
      result.database = {
        saved: dbResult.success,
        error: dbResult.error
      };

      if (dbResult.success && dbResult.signalId) {
        result.signalId = dbResult.signalId;
        signal.id = dbResult.signalId; // Update signal with ID for subsequent operations
      } else {
        result.success = false;
      }
    }

    // 2. Send to Discord
    if (sendToDiscord) {
      const discordResult = await deliverSignalToDiscord(signal);
      result.discord = {
        sent: discordResult.success,
        messageId: discordResult.messageId,
        error: discordResult.error
      };

      if (!discordResult.success) {
        result.success = false;
      }
    }

    // 3. Execute on IB Gateway (Paper Trading)
    if (executeOnIBGateway) {
      const ibResult = await executeSignalOnIBGateway(signal, positionSize);
      result.ibGateway = {
        executed: ibResult.success,
        orderId: ibResult.orderId,
        error: ibResult.error
      };

      if (!ibResult.success) {
        result.success = false;
      }
    }

    // 4. Send email notification (future implementation)
    if (sendEmail) {
      // TODO: Implement email delivery
      result.email = {
        sent: false,
        error: 'Email delivery not yet implemented'
      };
    }

    return result;

  } catch (error) {
    console.error('❌ Signal delivery pipeline failed:', error);
    return {
      success: false,
      discord: {
        sent: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      }
    };
  }
}

/**
 * Log signal delivery attempt to database
 */
async function logSignalDelivery(
  signalId: string,
  channel: 'discord' | 'email' | 'sms',
  status: 'delivered' | 'failed',
  errorMessage?: string
): Promise<void> {
  try {
    await supabase
      .from('signal_deliveries')
      .insert({
        signal_id: signalId,
        channel,
        status,
        error_message: errorMessage,
        delivered_at: status === 'delivered' ? new Date().toISOString() : null,
        attempted_at: new Date().toISOString()
      });
  } catch (error) {
    console.error('Failed to log signal delivery:', error);
    // Don't throw - logging failure shouldn't break the main flow
  }
}

/**
 * Get signal delivery history
 */
export async function getSignalDeliveryHistory(signalId: string): Promise<any[]> {
  try {
    const { data, error } = await supabase
      .from('signal_deliveries')
      .select('*')
      .eq('signal_id', signalId)
      .order('attempted_at', { ascending: false });

    if (error) {
      console.error('Failed to get delivery history:', error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error('Error getting delivery history:', error);
    return [];
  }
}

/**
 * Retry failed signal delivery
 */
export async function retrySignalDelivery(signalId: string): Promise<SignalDeliveryResult> {
  try {
    // Get signal from database
    const { data: signal, error } = await supabase
      .from('trading_signals')
      .select('*')
      .eq('id', signalId)
      .single();

    if (error || !signal) {
      return {
        success: false,
        discord: {
          sent: false,
          error: 'Signal not found'
        }
      };
    }

    // Retry delivery
    return await deliverSignal(signal, {
      sendToDiscord: true,
      saveToDatabase: false // Already saved
    });

  } catch (error) {
    return {
      success: false,
      discord: {
        sent: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      }
    };
  }
}

export default {
  deliverSignal,
  deliverSignalToDiscord,
  saveSignalToDatabase,
  getSignalDeliveryHistory,
  retrySignalDelivery
};
